logs:
  general:
    level: DEBUG
  access:
    enabled: true
    format: json

additionalArguments:
  - "--certificatesresolvers.le-staging.acme.tlschallenge=true"
  - "--certificatesresolvers.le-staging.acme.email=<FIXME>"
  - "--certificatesresolvers.le-staging.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.le.acme.tlschallenge=true"
  - "--certificatesresolvers.le.acme.email=<FIXME>"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--metrics.prometheus=true"
persistence:
  enabled: true
